version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    commit-message:
      prefix: "chore(deps)"
      include: scope
    labels:
      - deps
      - automated
    reviewers:
      - subvincdebian
    ignore:
      - dependency-name: "react-native"
      - dependency-name: "expo"
      - dependency-name: "expo-status-bar"
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - "minor"
          - "patch"
      dev-dependencies:
        dependency-type: development
        update-types:
          - "minor"
          - "patch"


  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/setup-node-deps"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(ci)"
      include: scope
    labels:
      - ci
      - automated
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directories:
      - "/apps/backend"
      - "/apps/web"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(infra)"
      include: scope
    labels:
      - infra
      - automated
