-- Independent profile effect inventory. No grants and no active-choice changes.
CREATE TABLE profile_effects (
 id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,name TEXT NOT NULL,description TEXT NOT NULL,
 family TEXT NOT NULL,variant TEXT NOT NULL,asset_type TEXT NOT NULL DEFAULT 'animated_webp',
 asset_url TEXT NOT NULL,preview_url TEXT NOT NULL,width INTEGER NOT NULL DEFAULT 640,height INTEGER NOT NULL DEFAULT 1120,
 fps DOUBLE PRECISION NOT NULL DEFAULT 60,duration_ms INTEGER NOT NULL DEFAULT 8000,
 avatar_anchor_x DOUBLE PRECISION NOT NULL DEFAULT 0.16,avatar_anchor_y DOUBLE PRECISION NOT NULL DEFAULT 0.22,
 rarity "DecorationRarity" NOT NULL DEFAULT 'epic',price_cents INTEGER NOT NULL DEFAULT 199,is_available BOOLEAN NOT NULL DEFAULT FALSE,
 CONSTRAINT profile_effects_media_check CHECK(width>0 AND height>0 AND fps>0 AND duration_ms>0 AND price_cents>=0 AND avatar_anchor_x BETWEEN 0 AND 1 AND avatar_anchor_y BETWEEN 0 AND 1 AND family IN ('sword','dragon','racing') AND asset_type='animated_webp')
);
CREATE TABLE user_profile_effects (
 user_id TEXT NOT NULL,profile_effect_id TEXT NOT NULL,purchased_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,profile_effect_id),
 FOREIGN KEY(user_id) REFERENCES "User"(id) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY(profile_effect_id) REFERENCES profile_effects(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX user_profile_effects_profile_effect_id_idx ON user_profile_effects(profile_effect_id);
ALTER TABLE "User" ADD COLUMN active_profile_effect_id TEXT;
ALTER TABLE "User" ADD CONSTRAINT "User_active_profile_effect_id_fkey" FOREIGN KEY(active_profile_effect_id) REFERENCES profile_effects(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "User_active_profile_effect_owned_fkey" FOREIGN KEY(id,active_profile_effect_id) REFERENCES user_profile_effects(user_id,profile_effect_id) ON DELETE NO ACTION ON UPDATE NO ACTION;
CREATE INDEX "User_active_profile_effect_id_idx" ON "User"(active_profile_effect_id);
INSERT INTO profile_effects(id,slug,name,description,family,variant,asset_url,preview_url) VALUES
('profile-effect-sword-kirito','profile-effect-sword-kirito','Kirito • Jade Slash','Объёмный меч наносит взмах, раскрывая светящиеся цифровые осколки. После короткой сцены профиль остаётся свободным для чтения.','sword','kirito','/Profile-decorations/Profile-effects/profile-effect-sword-kirito.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-sword-kirito.preview.webp?v=1'),
('profile-effect-sword-elucidator','profile-effect-sword-elucidator','Elucidator • Midnight Break','Объёмный меч наносит взмах, раскрывая светящиеся цифровые осколки. После короткой сцены профиль остаётся свободным для чтения.','sword','elucidator','/Profile-decorations/Profile-effects/profile-effect-sword-elucidator.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-sword-elucidator.preview.webp?v=1'),
('profile-effect-sword-blue-rose','profile-effect-sword-blue-rose','Blue Rose • Frost Shatter','Объёмный меч наносит взмах, раскрывая светящиеся цифровые осколки. После короткой сцены профиль остаётся свободным для чтения.','sword','blue-rose','/Profile-decorations/Profile-effects/profile-effect-sword-blue-rose.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-sword-blue-rose.preview.webp?v=1'),
('profile-effect-sword-excalibur','profile-effect-sword-excalibur','Excalibur • Golden Ascension','Объёмный меч наносит взмах, раскрывая светящиеся цифровые осколки. После короткой сцены профиль остаётся свободным для чтения.','sword','excalibur','/Profile-decorations/Profile-effects/profile-effect-sword-excalibur.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-sword-excalibur.preview.webp?v=1'),
('profile-effect-dragon-gold','profile-effect-dragon-gold','Dragon • Gold','Выразительный дракон вылетает от аватара, изгибает тело и ныряет через профиль. Хвост, лапы и усы следуют за движением.','dragon','gold','/Profile-decorations/Profile-effects/profile-effect-dragon-gold.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-dragon-gold.preview.webp?v=1'),
('profile-effect-dragon-blue','profile-effect-dragon-blue','Dragon • Sapphire','Выразительный дракон вылетает от аватара, изгибает тело и ныряет через профиль. Хвост, лапы и усы следуют за движением.','dragon','blue','/Profile-decorations/Profile-effects/profile-effect-dragon-blue.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-dragon-blue.preview.webp?v=1'),
('profile-effect-dragon-black','profile-effect-dragon-black','Dragon • Obsidian','Выразительный дракон вылетает от аватара, изгибает тело и ныряет через профиль. Хвост, лапы и усы следуют за движением.','dragon','black','/Profile-decorations/Profile-effects/profile-effect-dragon-black.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-dragon-black.preview.webp?v=1'),
('profile-effect-dragon-silver','profile-effect-dragon-silver','Dragon • Silver','Выразительный дракон вылетает от аватара, изгибает тело и ныряет через профиль. Хвост, лапы и усы следуют за движением.','dragon','silver','/Profile-decorations/Profile-effects/profile-effect-dragon-silver.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-dragon-silver.preview.webp?v=1'),
('profile-effect-dragon-red','profile-effect-dragon-red','Dragon • Crimson','Выразительный дракон вылетает от аватара, изгибает тело и ныряет через профиль. Хвост, лапы и усы следуют за движением.','dragon','red','/Profile-decorations/Profile-effects/profile-effect-dragon-red.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-dragon-red.preview.webp?v=1'),
('profile-effect-dragon-green','profile-effect-dragon-green','Dragon • Emerald','Выразительный дракон вылетает от аватара, изгибает тело и ныряет через профиль. Хвост, лапы и усы следуют за движением.','dragon','green','/Profile-decorations/Profile-effects/profile-effect-dragon-green.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-dragon-green.preview.webp?v=1'),
('profile-effect-dragon-purple','profile-effect-dragon-purple','Dragon • Amethyst','Выразительный дракон вылетает от аватара, изгибает тело и ныряет через профиль. Хвост, лапы и усы следуют за движением.','dragon','purple','/Profile-decorations/Profile-effects/profile-effect-dragon-purple.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-dragon-purple.preview.webp?v=1'),
('profile-effect-racing-kart','profile-effect-racing-kart','Kart • Neon Apex','Гоночная машина выезжает от аватара, проходит поворот со световым следом и ускоряется за пределы профиля. Колёса вращаются в 3D.','racing','kart','/Profile-decorations/Profile-effects/profile-effect-racing-kart.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-racing-kart.preview.webp?v=1'),
('profile-effect-racing-formula','profile-effect-racing-formula','Formula • Slipstream','Гоночная машина выезжает от аватара, проходит поворот со световым следом и ускоряется за пределы профиля. Колёса вращаются в 3D.','racing','formula','/Profile-decorations/Profile-effects/profile-effect-racing-formula.webp?v=1','/Profile-decorations/Profile-effects/profile-effect-racing-formula.preview.webp?v=1');
INSERT INTO nameplates(id,slug,name,description,asset_type,asset_url,preview_url,width,height,fps,duration_ms,shade_opacity,rarity,price_cents,is_available) VALUES
('nameplate-racing-kart','nameplate-racing-kart','Neon Kart Circuit','Настоящая 3D-модель проходит повороты с вращением колёс и затухающим световым следом. Спокойная левая часть сохраняет читаемость имени.','video','/Profile-decorations/Nameplates/nameplate-racing-kart.mp4?v=1','/Profile-decorations/Nameplates/nameplate-racing-kart.preview.webp?v=1',640,112,60,3000,.42,'epic',199,FALSE),
('nameplate-racing-formula','nameplate-racing-formula','Formula Blue Circuit','Настоящая 3D-модель проходит повороты с вращением колёс и затухающим световым следом. Спокойная левая часть сохраняет читаемость имени.','video','/Profile-decorations/Nameplates/nameplate-racing-formula.mp4?v=1','/Profile-decorations/Nameplates/nameplate-racing-formula.preview.webp?v=1',640,112,60,3000,.42,'epic',199,FALSE);
