-- Seven closed, paid sword and hoodie decorations. No public inventory grants.
INSERT INTO avatar_decorations (id,name,slug,description,asset_type,asset_url,preview_url,rarity,price_cents,is_available,render_scale) VALUES
('sao-blade-kirito','SAO Blade · Kirito','sao-blade-kirito','Клинок Кирито делает объёмный взмах. Бирюзовые кристаллические осколки мерцают и растворяются у края аватара.','animated_webp','/Profile-decorations/Avatar-decorations/sao-blade-kirito.webp?v=1','/Profile-decorations/Avatar-decorations/sao-blade-kirito.preview.webp?v=1','epic',199,FALSE,1.775),
('sao-blade-elucidator','SAO Blade · Elucidator','sao-blade-elucidator','Чёрный Elucidator с холодным стальным отблеском и синим свечением. Взмах сопровождает распад на светящиеся фрагменты.','animated_webp','/Profile-decorations/Avatar-decorations/sao-blade-elucidator.webp?v=1','/Profile-decorations/Avatar-decorations/sao-blade-elucidator.preview.webp?v=1','epic',199,FALSE,1.775),
('sao-blade-blue-rose','SAO Blade · Blue Rose','sao-blade-blue-rose','Серебристый клинок, кобальтовая гарда и светящийся голубой камень. Ледяные осколки плавно расходятся вокруг аватара.','animated_webp','/Profile-decorations/Avatar-decorations/sao-blade-blue-rose.webp?v=1','/Profile-decorations/Avatar-decorations/sao-blade-blue-rose.preview.webp?v=1','epic',199,FALSE,1.775),
('sao-blade-excalibur','SAO Blade · Excalibur','sao-blade-excalibur','Золотой Excalibur с бирюзовыми камнями делает мягкий взмах, оставляя тёплое сияние и золотые кристаллы.','animated_webp','/Profile-decorations/Avatar-decorations/sao-blade-excalibur.webp?v=1','/Profile-decorations/Avatar-decorations/sao-blade-excalibur.preview.webp?v=1','epic',199,FALSE,1.775),
('sao-dual-kirito-elucidator','SAO Dual · Kirito & Elucidator','sao-dual-kirito-elucidator','Клинок Кирито и Elucidator попеременно скрещиваются перед аватаром. Бирюзовые треугольные фрагменты рассыпаются и исчезают.','animated_webp','/Profile-decorations/Avatar-decorations/sao-dual-kirito-elucidator.webp?v=1','/Profile-decorations/Avatar-decorations/sao-dual-kirito-elucidator.preview.webp?v=1','epic',199,FALSE,1.775),
('sao-dual-blue-rose-excalibur','SAO Dual · Blue Rose & Excalibur','sao-dual-blue-rose-excalibur','Ледяной Blue Rose и золотой Excalibur чередуют взмахи в глубине. Голубые и золотые осколки создают двухцветный эффект распада.','animated_webp','/Profile-decorations/Avatar-decorations/sao-dual-blue-rose-excalibur.webp?v=1','/Profile-decorations/Avatar-decorations/sao-dual-blue-rose-excalibur.preview.webp?v=1','epic',199,FALSE,1.775),
('cipher-hood','Cipher Hood','cipher-hood','Объёмный графитовый капюшон плавно поднимается и колышется. У краёв аватара проявляются и затухают зелёные потоки двоичного кода.','animated_webp','/Profile-decorations/Avatar-decorations/cipher-hood.webp?v=1','/Profile-decorations/Avatar-decorations/cipher-hood.preview.webp?v=1','epic',199,FALSE,1.775);
