-- Independent profile-card frames, unrelated to avatar frames or effects.
CREATE TABLE profile_frames (
 id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,name TEXT NOT NULL,description TEXT NOT NULL,
 family TEXT NOT NULL,variant TEXT NOT NULL,color TEXT NOT NULL,accent TEXT NOT NULL,
 crown_url TEXT NOT NULL,crown_preview_url TEXT NOT NULL,corner_url TEXT NOT NULL,rail_url TEXT NOT NULL,footer_url TEXT NOT NULL,
 animated BOOLEAN NOT NULL DEFAULT FALSE,fps DOUBLE PRECISION NOT NULL DEFAULT 0,duration_ms INTEGER NOT NULL DEFAULT 3000,
 rarity "DecorationRarity" NOT NULL DEFAULT 'epic',price_cents INTEGER NOT NULL DEFAULT 199,is_available BOOLEAN NOT NULL DEFAULT FALSE,
 CONSTRAINT profile_frames_media_check CHECK(family IN ('dragon','rose','blade','crystal','celestial','cat') AND color ~ '^#[0-9a-fA-F]{6}$' AND accent ~ '^#[0-9a-fA-F]{6}$' AND duration_ms>0 AND fps>=0 AND price_cents>=0 AND (NOT animated OR fps>0))
);
CREATE TABLE user_profile_frames (
 user_id TEXT NOT NULL,profile_frame_id TEXT NOT NULL,purchased_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(user_id,profile_frame_id),
 FOREIGN KEY(user_id) REFERENCES "User"(id) ON DELETE CASCADE ON UPDATE CASCADE,
 FOREIGN KEY(profile_frame_id) REFERENCES profile_frames(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX user_profile_frames_profile_frame_id_idx ON user_profile_frames(profile_frame_id);
ALTER TABLE "User" ADD COLUMN active_profile_frame_id TEXT;
ALTER TABLE "User" ADD CONSTRAINT "User_active_profile_frame_id_fkey" FOREIGN KEY(active_profile_frame_id) REFERENCES profile_frames(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "User_active_profile_frame_owned_fkey" FOREIGN KEY(id,active_profile_frame_id) REFERENCES user_profile_frames(user_id,profile_frame_id) ON DELETE NO ACTION ON UPDATE NO ACTION;
CREATE INDEX "User_active_profile_frame_id_idx" ON "User"(active_profile_frame_id);
INSERT INTO profile_frames(id,slug,name,description,family,variant,color,accent,crown_url,crown_preview_url,corner_url,rail_url,footer_url,animated,fps,duration_ms,rarity,price_cents,is_available) VALUES
('profile-frame-dragon-jade','profile-frame-dragon-jade','Dragon Court • Jade','Два китайских дракона охраняют верх профиля. Резные углы, эмалевые детали и тихие блики обрамляют карточку.','dragon','dragon-jade','#32d6a2','#ddffd7','/Profile-decorations/Profile-frames/profile-frame-dragon-jade.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-jade.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-jade.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-jade.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-jade.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-dragon-sapphire','profile-frame-dragon-sapphire','Dragon Court • Sapphire','Два китайских дракона охраняют верх профиля. Резные углы, эмалевые детали и тихие блики обрамляют карточку.','dragon','dragon-sapphire','#219bff','#ccefff','/Profile-decorations/Profile-frames/profile-frame-dragon-sapphire.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-sapphire.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-sapphire.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-sapphire.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-sapphire.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-dragon-gold','profile-frame-dragon-gold','Dragon Court • Gold','Два китайских дракона охраняют верх профиля. Резные углы, эмалевые детали и тихие блики обрамляют карточку.','dragon','dragon-gold','#ffc54c','#fff4cb','/Profile-decorations/Profile-frames/profile-frame-dragon-gold.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-gold.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-gold.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-gold.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-dragon-gold.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-rose-ivory','profile-frame-rose-ivory','Velvet Filigree • Ivory','Объёмные бархатные розы, тонкие побеги и металлическая филигрань. Лепестки слегка раскрываются, оставляя центр профиля свободным.','rose','rose-ivory','#dacdeb','#fff8ef','/Profile-decorations/Profile-frames/profile-frame-rose-ivory.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-ivory.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-ivory.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-ivory.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-ivory.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-rose-crimson','profile-frame-rose-crimson','Velvet Filigree • Crimson','Объёмные бархатные розы, тонкие побеги и металлическая филигрань. Лепестки слегка раскрываются, оставляя центр профиля свободным.','rose','rose-crimson','#f34669','#ffd7d5','/Profile-decorations/Profile-frames/profile-frame-rose-crimson.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-crimson.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-crimson.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-crimson.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-crimson.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-rose-amethyst','profile-frame-rose-amethyst','Velvet Filigree • Amethyst','Объёмные бархатные розы, тонкие побеги и металлическая филигрань. Лепестки слегка раскрываются, оставляя центр профиля свободным.','rose','rose-amethyst','#a878ed','#eed9ff','/Profile-decorations/Profile-frames/profile-frame-rose-amethyst.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-amethyst.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-amethyst.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-amethyst.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-rose-amethyst.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-blade-jade','profile-frame-blade-jade','Twin Blades • Eclipse','Наши 3D-мечи образуют герб над профилем. Грани ловят свет, а цифровые детали украшают углы рамки.','blade','blade-jade','#38dfb5','#cdfbf1','/Profile-decorations/Profile-frames/profile-frame-blade-jade.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-blade-jade.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-blade-jade.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-blade-jade.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-blade-jade.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-blade-frost','profile-frame-blade-frost','Twin Blades • Frost & Gold','Наши 3D-мечи образуют герб над профилем. Грани ловят свет, а цифровые детали украшают углы рамки.','blade','blade-frost','#52c9fa','#ffe8a3','/Profile-decorations/Profile-frames/profile-frame-blade-frost.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-blade-frost.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-blade-frost.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-blade-frost.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-blade-frost.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-crystal-aurora','profile-frame-crystal-aurora','Aurora Reliquary','Наш 3D-кристалл плавно вращается над профилем. Перламутровая оправа и маленькие звёзды поддерживают его сияние.','crystal','crystal-aurora','#53ddeb','#ddd1ff','/Profile-decorations/Profile-frames/profile-frame-crystal-aurora.crown.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-crystal-aurora.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-crystal-aurora.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-crystal-aurora.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-crystal-aurora.footer.svg?v=1',TRUE,60,3000,'epic',199,FALSE),
('profile-frame-celestial-midnight','profile-frame-celestial-midnight','Celestial Observatory','Небесный медальон, орбиты и созвездия на тонкой золотой оправе. Звёзды спокойно мерцают по краям.','celestial','celestial-midnight','#d9ad56','#e4edff','/Profile-decorations/Profile-frames/profile-frame-celestial-midnight.crown.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-celestial-midnight.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-celestial-midnight.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-celestial-midnight.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-celestial-midnight.footer.svg?v=1',FALSE,0,6000,'epic',199,FALSE),
('profile-frame-cat-ivory','profile-frame-cat-ivory','Cloud Cat • Ivory','Мягкие ушки и лапки лежат на верхнем крае профиля. Маленькие искры мерцают, а хвост обнимает нижний угол.','cat','cat-ivory','#e9b9c5','#fff2e5','/Profile-decorations/Profile-frames/profile-frame-cat-ivory.crown.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-cat-ivory.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-cat-ivory.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-cat-ivory.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-cat-ivory.footer.svg?v=1',FALSE,0,6000,'epic',199,FALSE),
('profile-frame-cat-midnight','profile-frame-cat-midnight','Cloud Cat • Midnight','Мягкие ушки и лапки лежат на верхнем крае профиля. Маленькие искры мерцают, а хвост обнимает нижний угол.','cat','cat-midnight','#ac87d2','#ffcb89','/Profile-decorations/Profile-frames/profile-frame-cat-midnight.crown.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-cat-midnight.crown.preview.webp?v=1','/Profile-decorations/Profile-frames/profile-frame-cat-midnight.corner.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-cat-midnight.rail.svg?v=1','/Profile-decorations/Profile-frames/profile-frame-cat-midnight.footer.svg?v=1',FALSE,0,6000,'epic',199,FALSE);
